version: "3.7"
services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: nuttchai/rcie-proxy:1.0.8
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
